---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
- name: resource-tutorial

run:
  path: ENV TERM dumb && resource-tutorial/gradlew
  args: [--no-daemon build]